version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/node:8.9.3
    working_directory: ~/bogotajs-devops

    steps:
      - checkout
      - run: 
          name: install npm dependencies
          command: 'npm i'
      - save_cache: 
          key: dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules   
      - persist_to_workspace:
          root: ~/bogotajs-devops
          paths:
            - ./node_modules  
  test:
    docker: 
      - image: circleci/node:8.9.3
    working_directory: ~/bogotajs-devops    
    
    steps:    
      - checkout 
      - attach_workspace:
          at: ~/bogotajs-devops
      - run:
          name: runing test
          command: 'npm t'
  deploy:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/bogotajs-devops
    
    steps: 
      - checkout
      - attach_workspace:
          at: ~/bogotajs-devops
      - run:
          name: install now
          command: 'sudo npm i -g now'
      - run:     
          name: deploy qa
          command: now --docker -t $NOW_TOKEN




workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test      